# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: project-management-backend # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

  # you can overwrite defaults here
  #  stage: dev
  #  region: us-east-1

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - cognito-idp:AdminGetUser
        - cognito-idp:ListUsers
        - cognito-idp:AdminAddUserToGroup
      Resource:
        - "arn:aws:dynamodb:us-east-1:824057711072:table/projects"
        - "arn:aws:cognito-idp:us-east-1:824057711072:userpool/us-east-1_p0HFIGDim"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  list:
    handler: project/list.handler
    events:
      - http:
          method: GET
          path: projects
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:824057711072:userpool/us-east-1_p0HFIGDim
  create:
    handler: project/create.handler
    events:
      - http:
          method: POST
          path: projects
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:824057711072:userpool/us-east-1_p0HFIGDim
  delete:
    handler: project/delete.handler
    events:
      - http:
          method: DELETE
          path: projects/{id}
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:824057711072:userpool/us-east-1_p0HFIGDim
          request:
            parameters:
              paths:
                id: true
  update:
    handler: project/update.handler
    events:
      - http:
          method: PUT
          path: projects
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:824057711072:userpool/us-east-1_p0HFIGDim
  userlist:
    handler: users/list.handler
    events:
      - http:
          method: GET
          path: users
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:824057711072:userpool/us-east-1_p0HFIGDim
  usercreate:
    handler: users/create.handler
